version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running linter
      - npm run lint
  build:
    commands:
      - npm run dev
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
