version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.15.4
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g mocha
  pre_build:
    commands:
      - echo Running linter
  build:
    commands:
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
